
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.production': 'Production',
    'nav.company': 'Company',
    'nav.news': 'News',
    'nav.contacts': 'Contacts',
    'btn.ai': 'AI Consultant',
    'btn.quote': 'Get Quote',
    'hero.badge': 'Russian-Turkmen Joint Venture',
    'hero.title1': 'Advanced Packaging',
    'hero.title2': 'Manufacturing',
    'hero.desc': 'Full-cycle production of PET strapping and industrial packaging materials. Direct from our factory in Turkmenistan to your warehouse in Russia and Europe.',
    'hero.btn_products': 'View Products',
    'hero.btn_contact': 'Contact Sales',
    'stats.quality': 'Quality Control',
    'stats.quality_desc': 'ISO 9001 Certified manufacturing process with lab testing.',
    'stats.logistics': 'Global Logistics',
    'stats.logistics_desc': 'Strategic warehouses in Novosibirsk for rapid RU/EU delivery.',
    'stats.pricing': 'Direct Pricing',
    'stats.pricing_desc': 'No intermediaries. Factory direct pricing for bulk partners.',
    'intro.title': 'Reliable Load Securement',
    'intro.desc': 'TuranPET specializes in high-tensile PET strapping that outperforms steel in safety and elasticity. Whether you are securing lumber, bricks, or corrugated bales, our engineered polymers ensure your cargo arrives intact.',
    'catalog.title': 'Product Catalog',
    'catalog.subtitle': 'High-performance packaging solutions engineered for industrial applications. Browse our inventory of strapping, films, and tools.',
    'catalog.all': 'All Products',
    'catalog.view': 'View Details',
    'catalog.empty': 'No products found.',
    'subcat.all': 'All Types',
    'subcat.embossed': 'Embossed',
    'subcat.smooth': 'Smooth',
    'subcat.manual': 'Manual',
    'subcat.machine': 'Machine',
    'subcat.4-flap': '4-Flap Boxes',
    'subcat.food': 'Food Packaging',
    'subcat.self-assembling': 'Self-Assembling',
    'subcat.sheets': 'Sheets & Rolls',
    'subcat.battery': 'Battery Tools',
    'subcat.pneumatic': 'Pneumatic Tools',
    'subcat.buckles': 'Wire Buckles',
    'subcat.seals': 'Metal Seals',
    'prod.title': 'Full Cycle Production',
    'prod.subtitle': 'From raw bottle to secured load',
    'prod.overview_title': 'Vertically Integrated Ecosystem',
    'prod.overview_text': 'Our production facilities are located in the industrial hub of Mary, Turkmenistan. We have implemented a fully vertically integrated model: from our own network of PET collection points across the region to the manufacturing of the final product. The journey begins with primary sorting at collection sites, after which the raw material moves to our recycling workshop—located on the same territory as the extrusion line—ensuring process continuity and raw material purity. In the extrusion hall, equipped with modern machinery, flakes are transformed into high-tensile strap. Every batch undergoes rigorous auditing for break strength, elongation, straightness, weld strength, and split resistance. Finally, the product is packed onto our own manufactured pallets and stored for rapid shipment.',
    'prod.process_title': 'Manufacturing Process',
    'prod.step1_title': 'Collection & Sorting',
    'prod.step1_desc': 'Raw material arrives from collection points. Bottles are sorted by color and type, removing non-PET plastics, caps, labels, and debris.',
    'prod.step2_title': 'Crushing',
    'prod.step2_desc': 'Bottles pass through a crusher and are turned into PET flakes of the required size.',
    'prod.step3_title': 'Washing',
    'prod.step3_desc': 'Hot and cold washing with alkaline solutions removes glues, beverages, and contaminants, followed by a final rinse.',
    'prod.step4_title': 'Drying',
    'prod.step4_desc': 'Flakes undergo deep dehydration to reach low humidity levels required for stable melting.',
    'prod.step5_title': 'Melting & Extrusion',
    'prod.step5_desc': 'Raw material enters the extruder, melts at 260°C, is filtered, and passes through the die under pressure.',
    'prod.step6_title': 'Shaping',
    'prod.step6_desc': 'The molten preform is calibrated for precise thickness and geometry.',
    'prod.step7_title': 'Stretching',
    'prod.step7_desc': 'The strap undergoes heating and stretching (thermo-orientation) to achieve necessary mechanical strength.',
    'prod.step8_title': 'Embossing',
    'prod.step8_desc': 'Embossing is applied to the surface to increase grip for tools and friction welding.',
    'prod.step9_title': 'Cooling',
    'prod.step9_desc': 'The strap is stabilized and cooled to retain its form and characteristics.',
    'prod.step10_title': 'Winding',
    'prod.step10_desc': 'Finished strap is wound onto standard coils (406mm core) with precise tension.',
    'prod.step11_title': 'QC Testing',
    'prod.step11_desc': 'Every batch undergoes lab testing for geometry, split resistance, and tensile strength.',
    'prod.step12_title': 'Marking & Shipping',
    'prod.step12_desc': 'Coils are marked with batch data, packaged, and shipped to our warehouses.',
    'prod.lab_title': 'Laboratory Control',
    'prod.lab_desc': 'Our manufacturing plant in Mary is equipped with a state-of-the-art laboratory. We do not rely on third-party certification alone; we test every shift.',
    'prod.lab_test1': 'Break Strength Testing (ASTM D3950)',
    'prod.lab_test2': 'Elongation Recovery Analysis',
    'prod.lab_test3': 'Camber and Curl Measurement',
    'prod.lab_test4': 'Joint Efficiency Testing',
    'about.title': 'About TuranPET',
    'about.subtitle': 'A modern Russian-Turkmen enterprise setting new standards in industrial packaging manufacturing.',
    'about.h2': 'From Recycling to Manufacturing',
    'about.p1': 'TuranPET began in 2015 as a specialist in PET recycling and flake production. In 2023, we launched our own manufacturing line for PET strapping. Today, we produce all standard sizes and can accommodate custom specifications for dimensions and coil winding to meet unique production needs.',
    'about.p2': 'Our strategic manufacturing location allows for direct, cost-effective shipping to dealers across Russia. Logistics costs from Turkmenistan to major hubs like Moscow or Novosibirsk are optimized and consistent. Our Russian entity handles all customs clearance and import procedures, delivering ready-to-sell product directly to your warehouse with minimal lead time.',
    'about.p3': 'To provide a complete packaging ecosystem for our clients, we are expanding our product range. We now offer corrugated boxes, strapping tools, stretch film, and essential consumables like seals and buckles—making us your one-stop shop for industrial packaging.',
    'about.founded': 'Recycling Since',
    'about.output': 'Strap Since',
    'about.quote': 'We control quality from the raw flake to the final coil.',
    'about.val1_title': 'Sustainability',
    'about.val1_desc': 'Our "Bottle-to-Strap" technology reduces plastic waste. Our PET strap is 100% recyclable.',
    'about.val2_title': 'Quality Control',
    'about.val2_desc': 'Every batch undergoes tensile strength, elongation, and split resistance testing in our on-site laboratory.',
    'about.val3_title': 'Reliability',
    'about.val3_desc': 'With warehouses in Novosibirsk, we guarantee stable supply chains for our Russian and European partners.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Our logistics team is ready to assist you. Select a location below to view on map.',
    'contact.sales': 'Sales Department',
    'contact.sales_desc': 'Call us for quotes and technical consultation.',
    'contact.working_hours': 'Working Hours',
    'contact.mon_fri': 'Mon - Fri',
    'contact.sat': 'Saturday',
    'contact.sun': 'Sunday',
    'contact.closed': 'Closed',
    'contact.production_hq': 'Production & HQ',
    'contact.warehouses': 'Warehouses',
    'blog.title': 'News & Insights',
    'blog.subtitle': 'Updates from our production lines and the packaging industry.',
    'blog.read_more': 'Read More',
    'footer.desc': 'Full cycle manufacturer of PET strapping and packaging materials. Russian-Turkmen joint venture delivering quality since 2015.',
    'footer.rights': '© 2024 TuranPET Industrial Solutions. All rights reserved.',
    'footer.address_ru': 'Novosibirsk, Russia',
    'footer.address_tm': 'Mary, Turkmenistan',
    'cat.pet': 'PET Strap',
    'cat.film': 'Stretch Film',
    'cat.boxes': 'Boxes',
    'cat.tools': 'Tools',
    'cat.consumables': 'Consumables',
    'detail.back': 'Back to Catalog',
    'detail.quality': 'Quality Guaranteed',
    'detail.quality_sub': 'ISO 9001 Certified Production',
    'detail.shipping': 'Bulk Shipping',
    'detail.shipping_sub': 'Direct from Novosibirsk warehouse',
    'detail.specs': 'Technical Specifications',
    'detail.availability': 'Availability',
    'detail.instock': 'In Stock',
    'detail.req_quote': 'Request Quote',
    'detail.moq': 'Minimum order quantity applies for wholesale pricing.'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.products': 'Продукция',
    'nav.production': 'Производство',
    'nav.company': 'О компании',
    'nav.news': 'Блог',
    'nav.contacts': 'Контакты',
    'btn.ai': 'AI Консультант',
    'btn.quote': 'Заказать',
    'hero.badge': 'Российско-Туркменское СП',
    'hero.title1': 'Производство',
    'hero.title2': 'Упаковки',
    'hero.desc': 'Полный цикл производства ПЭТ-ленты и упаковочных материалов. Прямые поставки с завода в Туркменистане на ваш склад в России и Европе.',
    'hero.btn_products': 'Каталог',
    'hero.btn_contact': 'Связаться',
    'stats.quality': 'Контроль Качества',
    'stats.quality_desc': 'Производство сертифицировано ISO 9001. Собственная лаборатория.',
    'stats.logistics': 'Логистика',
    'stats.logistics_desc': 'Склады в Новосибирске для быстрой доставки по РФ и СНГ.',
    'stats.pricing': 'Прямые Цены',
    'stats.pricing_desc': 'Без посредников. Заводские цены для оптовых партнеров.',
    'intro.title': 'Надежная Фиксация Груза',
    'intro.desc': 'TuranPET специализируется на высокопрочной ПЭТ-ленте, превосходящей стальную по безопасности и эластичности. Будь то пиломатериалы, кирпич или прессованная макулатура, наши полимеры гарантируют сохранность вашего груза.',
    'catalog.title': 'Каталог Продукции',
    'catalog.subtitle': 'Высокоэффективные упаковочные решения для промышленности. ПЭТ-лента, стрейч-пленка и инструмент.',
    'catalog.all': 'Вся продукция',
    'catalog.view': 'Подробнее',
    'catalog.empty': 'Товары не найдены.',
    'subcat.all': 'Все типы',
    'subcat.embossed': 'Рифленая',
    'subcat.smooth': 'Гладкая',
    'subcat.manual': 'Ручная',
    'subcat.machine': 'Машинная',
    'subcat.4-flap': '4-х клапанные',
    'subcat.food': 'Для продуктов',
    'subcat.self-assembling': 'Самосборные',
    'subcat.sheets': 'Листы/Рулоны',
    'subcat.battery': 'Аккумуляторный',
    'subcat.pneumatic': 'Пневматический',
    'subcat.buckles': 'Пряжки',
    'subcat.seals': 'Скобы',
    'prod.title': 'Полный Цикл Производства',
    'prod.subtitle': 'От пластиковой бутылки до надежной ленты',
    'prod.overview_title': 'Вертикально-Интегрированная Экосистема',
    'prod.overview_text': 'Наш производственный комплекс расположен в г. Мары (Туркменистан). Мы реализовали модель полной вертикальной интеграции: от собственной сети пунктов сбора ПЭТ-тары по всей области до выпуска готовой продукции. Процесс начинается с первичной сортировки на наших заготовительных пунктах. Далее сырье поступает в цех переработки, расположенный на одной территории с линией экструзии, что гарантирует непрерывность процесса и чистоту получаемого ПЭТ-флекса. В соседнем цехе экструзии флекс превращается в высокопрочную ленту на современном оборудовании. Каждая партия проходит строгий контроль по 5 параметрам: разрывная нагрузка, удлинение, прямолинейность, прочность сварки и стойкость к расщеплению. Финальный этап — упаковка на поддоны собственного производства и размещение на складе готовой продукции для отправки клиентам.',
    'prod.process_title': 'Этапы производства',
    'prod.step1_title': 'Сбор и сортировка',
    'prod.step1_desc': 'Сырьё поступает из пунктов приёма. Бутылки сортируются по цвету и типу, удаляются посторонние пластики, крышки и этикетки.',
    'prod.step2_title': 'Дробление',
    'prod.step2_desc': 'Бутылки проходят через дробилку и превращаются в ПЭТ-флексу требуемого размера.',
    'prod.step3_title': 'Мойка',
    'prod.step3_desc': 'Горячая и холодная мойка в щелочных растворах удаляет клей, остатки напитков и примеси.',
    'prod.step4_title': 'Сушка',
    'prod.step4_desc': 'Флекса проходит дегидратацию до низкого уровня влажности для стабильного плавления.',
    'prod.step5_title': 'Экструзия',
    'prod.step5_desc': 'Сырьё плавится в экструдере при 260°C, фильтруется и под давлением проходит через фильеру.',
    'prod.step6_title': 'Формование',
    'prod.step6_desc': 'Расплавленная заготовка выравнивается по толщине и геометрии, приобретая форму ленты.',
    'prod.step7_title': 'Термоориентация',
    'prod.step7_desc': 'Лента проходит нагрев и вытяжку (стрейчинг), приобретая высокую механическую прочность.',
    'prod.step8_title': 'Рифление',
    'prod.step8_desc': 'На поверхность наносится тиснение (embossing) для увеличения сцепления с инструментом.',
    'prod.step9_title': 'Охлаждение',
    'prod.step9_desc': 'Лента стабилизируется в охлаждающих ваннах, сохраняя полученные характеристики.',
    'prod.step10_title': 'Намотка',
    'prod.step10_desc': 'Готовая лента с прецизионной точностью наматывается на катушки (шпули).',
    'prod.step11_title': 'Тестирование',
    'prod.step11_desc': 'Лабораторный контроль каждой партии: геометрия, разрывная нагрузка, удлинение.',
    'prod.step12_title': 'Отгрузка',
    'prod.step12_desc': 'Катушки маркируются, упаковываются на паллеты и отправляются клиентам.',
    'prod.lab_title': 'Лабораторный Контроль',
    'prod.lab_desc': 'Наш завод в г. Мары оснащен современной лабораторией. Мы тестируем каждую смену на разрывную нагрузку и удлинение.',
    'prod.lab_test1': 'Испытание на разрыв (ASTM D3950)',
    'prod.lab_test2': 'Анализ удлинения и восстановления',
    'prod.lab_test3': 'Измерение саблевидности и скручивания',
    'prod.lab_test4': 'Тестирование прочности соединения',
    'about.title': 'О компании TuranPET',
    'about.subtitle': 'Современное Российско-Туркменское предприятие, задающее стандарты качества.',
    'about.h2': 'От переработки до производства',
    'about.p1': 'TuranPET начал свой путь в 2015 году как переработчик ПЭТ-сырья, освоив выпуск высококачественного флекса. В 2023 году мы совершили технологический прорыв, запустив собственную линию по производству ПЭТ-ленты. Сегодня мы выпускаем полный спектр стандартных типоразмеров, а также готовы реализовать индивидуальные заказы на нестандартные размеры и намотку под специфические нужды вашего производства.',
    'about.p2': 'Стратегическое расположение нашего завода позволяет оптимизировать логистику и предлагать дилерам прямые поставки по всей России. Стоимость доставки из Туркменистана до Москвы или Новосибирска практически одинакова, что уравнивает условия для всех регионов. Наше российское представительство берет на себя все заботы по импорту, таможенному оформлению и доставке, обеспечивая поступление готовой к продаже продукции на ваш склад в кратчайшие сроки.',
    'about.p3': 'Стремясь стать комплексным поставщиком упаковочных решений, мы активно расширяем ассортимент. Помимо ПЭТ-ленты, мы предлагаем гофротару, специализированный инструмент, стрейч-пленку и необходимые расходные материалы — скобы и пряжки. Всё для надежной упаковки в одном месте.',
    'about.founded': 'Рециклинг с',
    'about.output': 'Лента с',
    'about.quote': 'Мы контролируем качество от флексы до готовой катушки.',
    'about.val1_title': 'Экологичность',
    'about.val1_desc': 'Наша технология "Bottle-to-Strap" сокращает пластиковые отходы. Наша ПЭТ-лента на 100% пригодна для вторичной переработки.',
    'about.val2_title': 'Контроль Качества',
    'about.val2_desc': 'Каждая партия проходит испытания на разрыв, удлинение и расщепление в нашей собственной лаборатории.',
    'about.val3_title': 'Надежность',
    'about.val3_desc': 'С собственными складами в Новосибирске мы гарантируем стабильные поставки для наших российских и европейских партнеров.',
    'contact.title': 'Контакты',
    'contact.subtitle': 'Наша команда логистики готова помочь. Выберите локацию на карте.',
    'contact.sales': 'Отдел Продаж',
    'contact.sales_desc': 'Звоните для расчета стоимости и консультаций.',
    'contact.working_hours': 'Часы Работы',
    'contact.mon_fri': 'Пн - Пт',
    'contact.sat': 'Суббота',
    'contact.sun': 'Воскресенье',
    'contact.closed': 'Выходной',
    'contact.production_hq': 'Производство и Офис',
    'contact.warehouses': 'Склады',
    'blog.title': 'Новости и Блог',
    'blog.subtitle': 'Обновления производства и новости индустрии упаковки.',
    'blog.read_more': 'Читать далее',
    'footer.desc': 'Производитель полного цикла ПЭТ-ленты и упаковки. Российско-Туркменское качество с 2015 года.',
    'footer.rights': '© 2024 TuranPET Industrial Solutions. Все права защищены.',
    'footer.address_ru': 'г. Новосибирск, Россия',
    'footer.address_tm': 'г. Мары, Туркменистан',
    'cat.pet': 'ПЭТ Лента',
    'cat.film': 'Стрейч-пленка',
    'cat.boxes': 'Коробки',
    'cat.tools': 'Инструмент',
    'cat.consumables': 'Расходники',
    'detail.back': 'Назад в каталог',
    'detail.quality': 'Гарантия Качества',
    'detail.quality_sub': 'Сертификация ISO 9001',
    'detail.shipping': 'Оптовые Поставки',
    'detail.shipping_sub': 'Прямо со склада в Новосибирске',
    'detail.specs': 'Характеристики',
    'detail.availability': 'Наличие',
    'detail.instock': 'В наличии',
    'detail.req_quote': 'Запросить цену',
    'detail.moq': 'Действуют минимальные партии для опта.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru'); // Default to Russian given the context

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
