import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.production': 'Production',
    'nav.company': 'Company',
    'nav.news': 'News',
    'nav.contacts': 'Contacts',
    'btn.ai': 'AI Consultant',
    'btn.quote': 'Get Quote',
    'hero.badge': 'Russian-Turkmen Joint Venture',
    'hero.title1': 'Advanced Packaging',
    'hero.title2': 'Manufacturing',
    'hero.desc': 'Full-cycle production of PET strapping and industrial packaging materials. Direct from our factory in Turkmenistan to your warehouse in Russia and Europe.',
    'hero.btn_products': 'View Products',
    'hero.btn_contact': 'Contact Sales',
    'stats.quality': 'Quality Control',
    'stats.quality_desc': 'ISO 9001 Certified manufacturing process with lab testing.',
    'stats.logistics': 'Global Logistics',
    'stats.logistics_desc': 'Strategic warehouses in Novosibirsk for rapid RU/EU delivery.',
    'stats.pricing': 'Direct Pricing',
    'stats.pricing_desc': 'No intermediaries. Factory direct pricing for bulk partners.',
    'intro.title': 'Reliable Load Securement',
    'intro.desc': 'TuranPET specializes in high-tensile PET strapping that outperforms steel in safety and elasticity. Whether you are securing lumber, bricks, or corrugated bales, our engineered polymers ensure your cargo arrives intact.',
    'catalog.title': 'Product Catalog',
    'catalog.subtitle': 'High-performance packaging solutions engineered for industrial applications. Browse our inventory of strapping, films, and tools.',
    'catalog.all': 'All Products',
    'catalog.view': 'View Details',
    'catalog.empty': 'No products found.',
    'subcat.all': 'All Types',
    'subcat.embossed': 'Embossed',
    'subcat.smooth': 'Smooth',
    'subcat.manual': 'Manual',
    'subcat.machine': 'Machine',
    'subcat.4-flap': '4-Flap Boxes',
    'subcat.food': 'Food Packaging',
    'subcat.self-assembling': 'Self-Assembling',
    'subcat.sheets': 'Sheets & Rolls',
    'subcat.battery': 'Battery Tools',
    'subcat.pneumatic': 'Pneumatic Tools',
    'subcat.buckles': 'Wire Buckles',
    'subcat.seals': 'Metal Seals',
    'prod.title': 'Full Cycle Production',
    'prod.subtitle': 'From raw bottle to secured load',
    'prod.process_title': 'Manufacturing Process',
    'prod.step1_title': 'Collection & Sorting',
    'prod.step1_desc': 'Raw material arrives from collection points. Bottles are sorted by color and type, removing non-PET plastics, caps, labels, and debris.',
    'prod.step2_title': 'Crushing',
    'prod.step2_desc': 'Bottles pass through a crusher and are turned into PET flakes of the required size.',
    'prod.step3_title': 'Washing',
    'prod.step3_desc': 'Hot and cold washing with alkaline solutions removes glues, beverages, and contaminants, followed by a final rinse.',
    'prod.step4_title': 'Drying',
    'prod.step4_desc': 'Flakes undergo deep dehydration to reach low humidity levels required for stable melting.',
    'prod.step5_title': 'Melting & Extrusion',
    'prod.step5_desc': 'Raw material enters the extruder, melts at 260°C, is filtered, and passes through the die under pressure.',
    'prod.step6_title': 'Shaping',
    'prod.step6_desc': 'The molten preform is calibrated for precise thickness and geometry.',
    'prod.step7_title': 'Stretching',
    'prod.step7_desc': 'The strap undergoes heating and stretching (thermo-orientation) to achieve necessary mechanical strength.',
    'prod.step8_title': 'Embossing',
    'prod.step8_desc': 'Embossing is applied to the surface to increase grip for tools and friction welding.',
    'prod.step9_title': 'Cooling',
    'prod.step9_desc': 'The strap is stabilized and cooled to retain its form and characteristics.',
    'prod.step10_title': 'Winding',
    'prod.step10_desc': 'Finished strap is wound onto standard coils (406mm core) with precise tension.',
    'prod.step11_title': 'QC Testing',
    'prod.step11_desc': 'Every batch undergoes lab testing for geometry, split resistance, and tensile strength.',
    'prod.step12_title': 'Marking & Shipping',
    'prod.step12_desc': 'Coils are marked with batch data, packaged, and shipped to our warehouses.',
    'prod.lab_title': 'Laboratory Control',
    'prod.lab_desc': 'Our manufacturing plant in Mary is equipped with a state-of-the-art laboratory. We do not rely on third-party certification alone; we test every shift.',
    'prod.lab_test1': 'Break Strength Testing (ASTM D3950)',
    'prod.lab_test2': 'Elongation Recovery Analysis',
    'prod.lab_test3': 'Camber and Curl Measurement',
    'prod.lab_test4': 'Joint Efficiency Testing',
    'about.title': 'About TuranPET',
    'about.subtitle': 'A modern Russian-Turkmen enterprise setting new standards in industrial packaging manufacturing.',
    'about.h2': 'Bridging Borders, Securing Cargo.',
    'about.p1': 'Founded as a strategic joint venture, TuranPET leverages the rich petrochemical resources of Turkmenistan and the logistical expertise of Russia. Our mission is to provide the Eurasian market with premium quality PET strapping and packaging materials at factory-direct prices.',
    'about.p2': 'Our production facility in Mary, Turkmenistan, operates a full-cycle recycling and extrusion process. We collect post-consumer PET bottles, process them into high-grade flakes (Hot Washed), and extrude them into strapping that meets ASTM and AAR standards.',
    'about.founded': 'Year Founded',
    'about.output': 'Monthly Output',
    'about.quote': 'We control quality from the raw flake to the final coil.',
    'about.val1_title': 'Sustainability',
    'about.val1_desc': 'Our "Bottle-to-Strap" technology reduces plastic waste. Our PET strap is 100% recyclable.',
    'about.val2_title': 'Quality Control',
    'about.val2_desc': 'Every batch undergoes tensile strength, elongation, and split resistance testing in our on-site laboratory.',
    'about.val3_title': 'Reliability',
    'about.val3_desc': 'With warehouses in Novosibirsk, we guarantee stable supply chains for our Russian and European partners.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Our logistics team is ready to assist you. Select a location below to view on map.',
    'contact.sales': 'Sales Department',
    'contact.sales_desc': 'Call us for quotes and technical consultation.',
    'contact.working_hours': 'Working Hours',
    'contact.mon_fri': 'Mon - Fri',
    'contact.sat': 'Saturday',
    'contact.sun': 'Sunday',
    'contact.closed': 'Closed',
    'contact.production_hq': 'Production & HQ',
    'contact.warehouses': 'Warehouses',
    'blog.title': 'News & Insights',
    'blog.subtitle': 'Updates from our production lines and the packaging industry.',
    'blog.read_more': 'Read More',
    'footer.desc': 'Full cycle manufacturer of PET strapping and packaging materials. Russian-Turkmen joint venture delivering quality since 2015.',
    'footer.rights': '© 2024 TuranPET Industrial Solutions. All rights reserved.',
    'footer.address_ru': 'Novosibirsk, Russia',
    'footer.address_tm': 'Mary, Turkmenistan',
    'cat.pet': 'PET Strap',
    'cat.film': 'Stretch Film',
    'cat.boxes': 'Boxes',
    'cat.tools': 'Tools',
    'cat.consumables': 'Consumables',
    'detail.back': 'Back to Catalog',
    'detail.quality': 'Quality Guaranteed',
    'detail.quality_sub': 'ISO 9001 Certified Production',
    'detail.shipping': 'Bulk Shipping',
    'detail.shipping_sub': 'Direct from Novosibirsk warehouse',
    'detail.specs': 'Technical Specifications',
    'detail.availability': 'Availability',
    'detail.instock': 'In Stock',
    'detail.req_quote': 'Request Quote',
    'detail.moq': 'Minimum order quantity applies for wholesale pricing.'
  },
  ru: {
    'nav.home': 'Главная',
    'nav.products': 'Продукция',
    'nav.production': 'Производство',
    'nav.company': 'О компании',
    'nav.news': 'Блог',
    'nav.contacts': 'Контакты',
    'btn.ai': 'AI Консультант',
    'btn.quote': 'Заказать',
    'hero.badge': 'Российско-Туркменское СП',
    'hero.title1': 'Производство',
    'hero.title2': 'Упаковки',
    'hero.desc': 'Полный цикл производства ПЭТ-ленты и упаковочных материалов. Прямые поставки с завода в Туркменистане на ваш склад в России и Европе.',
    'hero.btn_products': 'Каталог',
    'hero.btn_contact': 'Связаться',
    'stats.quality': 'Контроль Качества',
    'stats.quality_desc': 'Производство сертифицировано ISO 9001. Собственная лаборатория.',
    'stats.logistics': 'Логистика',
    'stats.logistics_desc': 'Склады в Новосибирске для быстрой доставки по РФ и СНГ.',
    'stats.pricing': 'Прямые Цены',
    'stats.pricing_desc': 'Без посредников. Заводские цены для оптовых партнеров.',
    'intro.title': 'Надежная Фиксация Груза',
    'intro.desc': 'TuranPET специализируется на высокопрочной ПЭТ-ленте, превосходящей стальную по безопасности и эластичности. Будь то пиломатериалы, кирпич или прессованная макулатура, наши полимеры гарантируют сохранность вашего груза.',
    'catalog.title': 'Каталог Продукции',
    'catalog.subtitle': 'Высокоэффективные упаковочные решения для промышленности. ПЭТ-лента, стрейч-пленка и инструмент.',
    'catalog.all': 'Вся продукция',
    'catalog.view': 'Подробнее',
    'catalog.empty': 'Товары не найдены.',
    'subcat.all': 'Все типы',
    'subcat.embossed': 'Рифленая',
    'subcat.smooth': 'Гладкая',
    'subcat.manual': 'Ручная',
    'subcat.machine': 'Машинная',
    'subcat.4-flap': '4-х клапанные',
    'subcat.food': 'Для продуктов',
    'subcat.self-assembling': 'Самосборные',
    'subcat.sheets': 'Листы/Рулоны',
    'subcat.battery': 'Аккумуляторный',
    'subcat.pneumatic': 'Пневматический',
    'subcat.buckles': 'Пряжки',
    'subcat.seals': 'Скобы',
    'prod.title': 'Полный Цикл Производства',
    'prod.subtitle': 'От пластиковой бутылки до надежной ленты',
    'prod.process_title': 'Этапы производства',
    'prod.step1_title': 'Сбор и сортировка',
    'prod.step1_desc': 'Сырьё поступает из пунктов приёма. Бутылки сортируются по цвету и типу, удаляются посторонние пластики, крышки и этикетки.',
    'prod.step2_title': 'Дробление',
    'prod.step2_desc': 'Бутылки проходят через дробилку и превращаются в ПЭТ-флексу требуемого размера.',
    'prod.step3_title': 'Мойка',
    'prod.step3_desc': 'Горячая и холодная мойка в щелочных растворах удаляет клей, остатки напитков и примеси.',
    'prod.step4_title': 'Сушка',
    'prod.step4_desc': 'Флекса проходит дегидратацию до низкого уровня влажности для стабильного плавления.',
    'prod.step5_title': 'Экструзия',
    'prod.step5_desc': 'Сырьё плавится в экструдере при 260°C, фильтруется и под давлением проходит через фильеру.',
    'prod.step6_title': 'Формование',
    'prod.step6_desc': 'Расплавленная заготовка выравнивается по толщине и геометрии, приобретая форму ленты.',
    'prod.step7_title': 'Термоориентация',
    'prod.step7_desc': 'Лента проходит нагрев и вытяжку (стрейчинг), приобретая высокую механическую прочность.',
    'prod.step8_title': 'Рифление',
    'prod.step8_desc': 'На поверхность наносится тиснение (embossing) для увеличения сцепления с инструментом.',
    'prod.step9_title': 'Охлаждение',
    'prod.step9_desc': 'Лента стабилизируется в охлаждающих ваннах, сохраняя полученные характеристики.',
    'prod.step10_title': 'Намотка',
    'prod.step10_desc': 'Готовая лента с прецизионной точностью наматывается на катушки (шпули).',
    'prod.step11_title': 'Тестирование',
    'prod.step11_desc': 'Лабораторный контроль каждой партии: геометрия, разрывная нагрузка, удлинение.',
    'prod.step12_title': 'Отгрузка',
    'prod.step12_desc': 'Катушки маркируются, упаковываются на паллеты и отправляются клиентам.',
    'prod.lab_title': 'Лабораторный Контроль',
    'prod.lab_desc': 'Наш завод в г. Мары оснащен современной лабораторией. Мы тестируем каждую смену на разрывную нагрузку и удлинение.',
    'prod.lab_test1': 'Испытание на разрыв (ASTM D3950)',
    'prod.lab_test2': 'Анализ удлинения и восстановления',
    'prod.lab_test3': 'Измерение саблевидности и скручивания',
    'prod.lab_test4': 'Тестирование прочности соединения',
    'about.title': 'О компании TuranPET',
    'about.subtitle': 'Современное Российско-Туркменское предприятие, задающее стандарты качества.',
    'about.h2': 'Объединяя границы, сохраняя груз.',
    'about.p1': 'Основанное как стратегическое совместное предприятие, TuranPET использует богатые нефтехимические ресурсы Туркменистана и логистический опыт России. Наша миссия — обеспечить рынок Евразии ПЭТ-лентой высшего качества по ценам завода-производителя.',
    'about.p2': 'Наше производство в г. Мары (Туркменистан) осуществляет полный цикл переработки. Мы производим ленту из 100% переработанного сырья, соответствующую стандартам ASTM и AAR.',
    'about.founded': 'Основание',
    'about.output': 'Ежемесячный объем',
    'about.quote': 'Мы контролируем качество от флексы до готовой катушки.',
    'about.val1_title': 'Экологичность',
    'about.val1_desc': 'Наша технология "Bottle-to-Strap" сокращает пластиковые отходы. Наша ПЭТ-лента на 100% пригодна для вторичной переработки.',
    'about.val2_title': 'Контроль Качества',
    'about.val2_desc': 'Каждая партия проходит испытания на разрыв, удлинение и расщепление в нашей собственной лаборатории.',
    'about.val3_title': 'Надежность',
    'about.val3_desc': 'С собственными складами в Новосибирске мы гарантируем стабильные поставки для наших российских и европейских партнеров.',
    'contact.title': 'Контакты',
    'contact.subtitle': 'Наша команда логистики готова помочь. Выберите локацию на карте.',
    'contact.sales': 'Отдел Продаж',
    'contact.sales_desc': 'Звоните для расчета стоимости и консультаций.',
    'contact.working_hours': 'Часы Работы',
    'contact.mon_fri': 'Пн - Пт',
    'contact.sat': 'Суббота',
    'contact.sun': 'Воскресенье',
    'contact.closed': 'Выходной',
    'contact.production_hq': 'Производство и Офис',
    'contact.warehouses': 'Склады',
    'blog.title': 'Новости и Блог',
    'blog.subtitle': 'Обновления производства и новости индустрии упаковки.',
    'blog.read_more': 'Читать далее',
    'footer.desc': 'Производитель полного цикла ПЭТ-ленты и упаковки. Российско-Туркменское качество с 2015 года.',
    'footer.rights': '© 2024 TuranPET Industrial Solutions. Все права защищены.',
    'footer.address_ru': 'г. Новосибирск, Россия',
    'footer.address_tm': 'г. Мары, Туркменистан',
    'cat.pet': 'ПЭТ Лента',
    'cat.film': 'Стрейч-пленка',
    'cat.boxes': 'Коробки',
    'cat.tools': 'Инструмент',
    'cat.consumables': 'Расходники',
    'detail.back': 'Назад в каталог',
    'detail.quality': 'Гарантия Качества',
    'detail.quality_sub': 'Сертификация ISO 9001',
    'detail.shipping': 'Оптовые Поставки',
    'detail.shipping_sub': 'Прямо со склада в Новосибирске',
    'detail.specs': 'Характеристики',
    'detail.availability': 'Наличие',
    'detail.instock': 'В наличии',
    'detail.req_quote': 'Запросить цену',
    'detail.moq': 'Действуют минимальные партии для опта.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru'); // Default to Russian given the context

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};